name: Makefile CI

on:
  # push:
  #   branches: [ "subrat-makefile" ]
  # pull_request:
  #   branches: [ "subrat-makefile" ]
  workflow_dispatch:
  

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Change directory to makefile_demo_cpp
      run: cd makefile_demo_cpp
    
    - name: Create directory
      run: mkdir build_dir     

    - name: Start build
      run: make

    - name: Run check
      run: make check

    - name: Run distcheck
      run: make distcheck
